version: "3.7"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ../.docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run dev"

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ../.docker/backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 1337:1337
    command: sh -c "npm install && npm run dev"

  db:
    container_name: db
    image: db
    build:
      context: .
      dockerfile: ./.docker/db/Dockerfile
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=strapi
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    container_name: cdp_phpmyadmin
    image: phpmyadmin:5.2
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root

volumes:
  db:
    name: db
